### ISSUE TITLE
Improve alternate mode

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mueller-ma/Coffee#177]
**Describe the bug**
The alternate mode should be able to collect previous system setting, after turning off Coffee, it should be able to restore system setting.

**To Reproduce**
1. Go to main interface
2. Click on Toggle Coffee
3. Click on Toggle Coffee again
4. Open System settings => Display
5. See error

**Expected behavior**
I’ve previously set screen timeout time as 1 minute. After I turned off Coffee, I saw it was just changed to 30 minutes.

**Screenshots**

**Device (please complete the following information):**
 - Device: Galaxy F52 5G
 - Android version: 12

**Additional context**

**Comment by mueller-ma** [comment]
That should be the case: https://github.com/mueller-ma/Coffee/blob/main/app/src/main/java/com/github/muellerma/coffee/ForegroundService.kt#L130

Can you set the screen timeout manually to 1 minute, turn on and off Coffee and check the screen timeout again? Do you see any message with "Coffee couldn't set the previous timeout"?

**Comment by KrasnayaPloshchad** [comment]
Ok I did, but I couldn’t reproduce now.

**Comment by KrasnayaPloshchad** [comment]
I think I found the way to reproduce:


1.   Go to main interface
2.    Click on Toggle Coffee
3.   Click on Next timeout
4.    Click on Toggle Coffee again
5.    Open System settings => Display
6.   See error

**Comment by sls1005** [comment]
I saw a similar bug. It happened after the first time I  switched to the alternate mode, turning Coffee on and of. My screen timeout had became very short since then. 15 secs, I guess. I cannot be sure because when I entered System > Display > Screen Timeout, my screen timeout was set to an option that I've never seen. It was set to `()`. (Yes, the option just named "`()`." Is it a system-level bug?) However, it no longer happens after I set the timeout to 1 min manually. It works fine since then. I'm on Galaxy M33 5G, with Android 13.

**Comment by mueller-ma** [comment]
> It was set to (). (Yes, the option just named "()." Is it a system-level bug?) 

Coffee sets the timeout in seconds and the OS only has a limited set of numbers that can be converted back to a human readable string. If Coffee sets a timeout that isn't in this limited set, the OS displays `()`.

**Comment by KrasnayaPloshchad** [comment]
I suggest creating a separate service to working for keeping awake, both main interface, notification and quick setting tile are used to enable, disable and configure this service.

**Comment by mueller-ma** [comment]
This is exactly what the default mode does and overly aggressive battery savers kill the service.
