### ISSUE TITLE
screen pressing

### ISSUE THREAD

**Issue by Wjxfi** [mueller-ma/Coffee#204]
**Describe the solution you'd like**
Pressing the screen as from a finger

need a choice of mode

every 9 seconds, 29 seconds, 59 seconds, 119 seconds, 299 seconds, 599 seconds

**Additional context**

there are autoclickers with open source code from which you can understand how to do it

**Comment by mueller-ma** [comment]
If Coffee presses the screen, wouldn't this cause unintended behavior, because of these random presses?

**Comment by mueller-ma** [comment]
There's no guaranty that there's always the battery charge. 

Coffee starts a wakelock when enabled which works on most devices. This may not work because of an overly aggressive battery saver that is implemented by some OEMs (including Poco, Samsung and Xiaomi). In that case please enable "Alternate mode" in the settings.
I want to focus on bug fixes of the existing issues and new features that are useful for most people.
