### ISSUE TITLE
I think your code will not work

### ISSUE THREAD

**Issue by lum7671** [mueller-ma/Coffee#27]
https://developer.android.com/training/scheduling/wakelock#screen

> Keep the screen on
> (and only in an activity, never in a service or other app component)
>
> class MainActivity : Activity() {
> window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
> }

----
> Keep the CPU on
> PowerManager.WakeLock

your code is for "Keep the CPU on" and 
your app is not activity (not exist window).

I desperately want your app to run well.

thanks

**Comment by mueller-ma** [comment]
> The best way to do this is to use the FLAG_KEEP_SCREEN_ON in your activity (and only in an activity, never in a service or other app component).

(from the linked page).

I agree with the documentation: Using this flag is better than holding a wakelock. But since it doesn't work for services, I have to hold a wakelock here (which I do).
The wakelock is released when the app is in background, but the persisitent notification is a foreground service and thus the wakelock isn't released.*

* At least on AOSP. Some vendors added custom "battery saver modes" that kill foreground services or wakelocks. See #16 for more information.
