### ISSUE TITLE
The app doesn't seem to work on my device

### ISSUE THREAD

**Issue by akrram0** [mueller-ma/Coffee#324]
When I download the app and enable it, its seems like the screen stays up (open on coffee app) but when switching to other app to study like YouTube (any app) the screen turns off so like the app only work when it's opens on coffee app even I try the alternative mode same problem.+ I don't want the app to be working 24/7 only when I enable it and when I disable it stop, by the way good app👍

Device info:
Oppo A74
Android 13
Coloros 13

**Comment by mueller-ma** [comment]
Did you grant any permissions after enabling alternative mode? Can you enable coffee and check what's the configured screen timeout? It should be set to the highest possible value then.
I can confirm Coffee is working on a stock Android 13, so it's most likely an overly aggressive battery saver, which is out of my control :/

**Comment by akrram0** [comment]
> Did you grant any permissions after enabling alternative mode? Can you enable coffee and check what's the configured screen timeout? It should be set to the highest possible value then. I can confirm Coffee is working on a stock Android 13, so it's most likely an overly aggressive battery saver, which is out of my control :/

Yup I granted it edit system settings and I'm pretty sure that doest has to do with battery saver because it's off and when I enable the quick tile icon and givit some time outside of the app it turn off the screen after some time i think it's like 30s (system default) and when I go to check on the icon I found it off and same thing with doing it inside the app
![Screenshot_2024-04-29-16-51-01-67_959e28baa4b356007146fb0e222e2f5d](https://github.com/mueller-ma/Coffee/assets/140515513/a6e8a29f-429e-452f-9c1c-141ab49946e7)
![Screenshot_2024-04-29-16-54-30-75_5734e8eb49b4234b62f913f831715b0f](https://github.com/mueller-ma/Coffee/assets/140515513/d37eb74b-9b2c-4200-9e25-c30db1747b95)
![Screenshot_2024-04-29-16-54-34-47_5734e8eb49b4234b62f913f831715b0f](https://github.com/mueller-ma/Coffee/assets/140515513/9a689e33-d35e-4b66-b806-2e8b56b95d2c)

**Comment by weiluntong** [comment]
Hey, maybe I should start my own thread, but I feel iffy doing that, because if every device had the same problem, we'd have hundreds of threads with the same title XD I hope that's OK.

I just wanted to chime in and say I'm experiencing the same issue. It's from the same R&D, if that helps. My phone is:

OnePlus 9 Pro (T-mobile Variant) 
Operating System: OxygenOS 14.0
Version: LE2127_14.0.0.220
All that being Android 14.

I also enabled Alternate mode, gave it the necessary permission to "modify system settings" and disabled battery optimization and allowed the app to run in the background.

After I turned on Coffee, I headed over to to "Display and Brightness" settings to check the "Auto screen off" value, and it has not changed from my preferred "15 seconds" with Coffee toggled on.

I'd like to also note that before the Android 14 update, it was actually working. I didn't even have to turn on "Alternate mode"

**Comment by DirAgAlok** [comment]
I had the same issue. After some month of not caring today i got into it. In my case it was the adaptive battery setting even though it was turned off.
So in settings -> battery -> adaptive battery -> restricted apps -> uncheck coffee (and maybe some other apps). 
I don't know why it was killing coffee (and other apps) even if it is turned off. I had issues with other apps as well like messeging apps where i did not or much later get notifications. 
I hope this helps

**Comment by diegomsg** [comment]
> I had the same issue. After some month of not caring today i got into it. In my case it was the adaptive battery setting even though it was turned off. So in settings -> battery -> adaptive battery -> restricted apps -> uncheck coffee (and maybe some other apps). I don't know why it was killing coffee (and other apps) even if it is turned off. I had issues with other apps as well like messeging apps where i did not or much later get notifications. I hope this helps

This worked for me. Thanks.
